// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: record.proto

package record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Records struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls []*Call `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
}

func (x *Records) Reset() {
	*x = Records{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Records) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Records) ProtoMessage() {}

func (x *Records) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Records.ProtoReflect.Descriptor instead.
func (*Records) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *Records) GetCalls() []*Call {
	if x != nil {
		return x.Calls
	}
	return nil
}

type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame    int32  `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	FuncName string `protobuf:"bytes,2,opt,name=funcName,proto3" json:"funcName,omitempty"`
	FuncArgs []byte `protobuf:"bytes,3,opt,name=funcArgs,proto3" json:"funcArgs,omitempty"`
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *Call) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *Call) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *Call) GetFuncArgs() []byte {
	if x != nil {
		return x.FuncArgs
	}
	return nil
}

type CreateShowObj1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewObjTag int32 `protobuf:"varint,1,opt,name=newObjTag,proto3" json:"newObjTag,omitempty"`
}

func (x *CreateShowObj1) Reset() {
	*x = CreateShowObj1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShowObj1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowObj1) ProtoMessage() {}

func (x *CreateShowObj1) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowObj1.ProtoReflect.Descriptor instead.
func (*CreateShowObj1) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShowObj1) GetNewObjTag() int32 {
	if x != nil {
		return x.NewObjTag
	}
	return 0
}

type ShowInf1F1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverTag int32 `protobuf:"varint,1,opt,name=receiverTag,proto3" json:"receiverTag,omitempty"`
}

func (x *ShowInf1F1) Reset() {
	*x = ShowInf1F1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowInf1F1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInf1F1) ProtoMessage() {}

func (x *ShowInf1F1) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInf1F1.ProtoReflect.Descriptor instead.
func (*ShowInf1F1) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *ShowInf1F1) GetReceiverTag() int32 {
	if x != nil {
		return x.ReceiverTag
	}
	return 0
}

type ShowInf1F2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverTag int32 `protobuf:"varint,1,opt,name=receiverTag,proto3" json:"receiverTag,omitempty"`
	ArgI1       int32 `protobuf:"varint,2,opt,name=argI1,proto3" json:"argI1,omitempty"`
}

func (x *ShowInf1F2) Reset() {
	*x = ShowInf1F2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowInf1F2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInf1F2) ProtoMessage() {}

func (x *ShowInf1F2) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInf1F2.ProtoReflect.Descriptor instead.
func (*ShowInf1F2) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{4}
}

func (x *ShowInf1F2) GetReceiverTag() int32 {
	if x != nil {
		return x.ReceiverTag
	}
	return 0
}

func (x *ShowInf1F2) GetArgI1() int32 {
	if x != nil {
		return x.ArgI1
	}
	return 0
}

type ShowInf1F3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverTag int32   `protobuf:"varint,1,opt,name=receiverTag,proto3" json:"receiverTag,omitempty"`
	ArgI1       int32   `protobuf:"varint,2,opt,name=argI1,proto3" json:"argI1,omitempty"`
	ArgI2       int32   `protobuf:"varint,3,opt,name=argI2,proto3" json:"argI2,omitempty"`
	ArgF1       float32 `protobuf:"fixed32,4,opt,name=argF1,proto3" json:"argF1,omitempty"`
	ArgF2       float32 `protobuf:"fixed32,5,opt,name=argF2,proto3" json:"argF2,omitempty"`
	ArgF3       float32 `protobuf:"fixed32,6,opt,name=argF3,proto3" json:"argF3,omitempty"`
	ArgS1       string  `protobuf:"bytes,7,opt,name=argS1,proto3" json:"argS1,omitempty"`
}

func (x *ShowInf1F3) Reset() {
	*x = ShowInf1F3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowInf1F3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInf1F3) ProtoMessage() {}

func (x *ShowInf1F3) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInf1F3.ProtoReflect.Descriptor instead.
func (*ShowInf1F3) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{5}
}

func (x *ShowInf1F3) GetReceiverTag() int32 {
	if x != nil {
		return x.ReceiverTag
	}
	return 0
}

func (x *ShowInf1F3) GetArgI1() int32 {
	if x != nil {
		return x.ArgI1
	}
	return 0
}

func (x *ShowInf1F3) GetArgI2() int32 {
	if x != nil {
		return x.ArgI2
	}
	return 0
}

func (x *ShowInf1F3) GetArgF1() float32 {
	if x != nil {
		return x.ArgF1
	}
	return 0
}

func (x *ShowInf1F3) GetArgF2() float32 {
	if x != nil {
		return x.ArgF2
	}
	return 0
}

func (x *ShowInf1F3) GetArgF3() float32 {
	if x != nil {
		return x.ArgF3
	}
	return 0
}

func (x *ShowInf1F3) GetArgS1() string {
	if x != nil {
		return x.ArgS1
	}
	return ""
}

var File_record_proto protoreflect.FileDescriptor

var file_record_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x73, 0x72, 0x63, 0x22, 0x2a, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1f,
	0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x73, 0x72, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x22,
	0x54, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x41, 0x72, 0x67, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x77, 0x4f, 0x62, 0x6a, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x4f, 0x62,
	0x6a, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x4f,
	0x62, 0x6a, 0x54, 0x61, 0x67, 0x22, 0x2e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66,
	0x31, 0x46, 0x31, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x54, 0x61, 0x67, 0x22, 0x44, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66,
	0x31, 0x46, 0x32, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x49, 0x31, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x72, 0x67, 0x49, 0x31, 0x22, 0xb2, 0x01, 0x0a, 0x0a,
	0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x31, 0x46, 0x33, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x72, 0x67, 0x49, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x72, 0x67,
	0x49, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x49, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x61, 0x72, 0x67, 0x49, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x46,
	0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x72, 0x67, 0x46, 0x31, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x72, 0x67, 0x46, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61,
	0x72, 0x67, 0x46, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x46, 0x33, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x72, 0x67, 0x46, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72,
	0x67, 0x53, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x72, 0x67, 0x53, 0x31,
	0x42, 0x13, 0x5a, 0x11, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData = file_record_proto_rawDesc
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_proto_rawDescData)
	})
	return file_record_proto_rawDescData
}

var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_record_proto_goTypes = []interface{}{
	(*Records)(nil),        // 0: src.Records
	(*Call)(nil),           // 1: src.Call
	(*CreateShowObj1)(nil), // 2: src.CreateShowObj1
	(*ShowInf1F1)(nil),     // 3: src.ShowInf1F1
	(*ShowInf1F2)(nil),     // 4: src.ShowInf1F2
	(*ShowInf1F3)(nil),     // 5: src.ShowInf1F3
}
var file_record_proto_depIdxs = []int32{
	1, // 0: src.Records.calls:type_name -> src.Call
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Records); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShowObj1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowInf1F1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowInf1F2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowInf1F3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_rawDesc = nil
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
